services:
  - type: web
    name: fraud-audit-dashboard
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    autoDeploy: true